// Generated by CoffeeScript 1.9.3
(function() {
  var client, mongo;

  mongo = require('mongodb').MongoClient;

  client = require('socket.io').listen(8080).sockets;

  mongo.connect('mongodb://127.0.0.1/chat', function(err, db) {
    if (err) {
      throw err;
    }
    return client.on('connection', function(socket) {
      var col, sendStatus;
      col = db.collection('messages');
      sendStatus = function(s) {
        return socket.emit('status', s);
      };
      col.find().limit(100).sort({
        _id: 1
      }).toArray(function(err, res) {
        if (err) {
          throw err;
        }
        return socket.emit('output', res);
      });
      return socket.on('input', function(data) {
        var message, name, whiteSpacePattern;
        name = data.name;
        message = data.message;
        whiteSpacePattern = /^\s*$/;
        if (whiteSpacePattern.test(name) || whiteSpacePattern.test(message)) {
          return sendStatus('Name and message is required.');
        } else {
          return col.insert({
            name: name,
            message: message
          }, function() {
            client.emit('output', [data]);
            return sendStatus({
              message: "Message Sent",
              clear: true
            });
          });
        }
      });
    });
  });

}).call(this);
